### ISSUE TITLE
it doesn't work .send post with form-data 

### ISSUE THREAD

**Issue by ccontarino** [driverdan/node-XMLHttpRequest#154]
package.json
"xmlhttprequest": "1.8.0",
"form-data": "2.3.1"

> var form = new FormData();
>   form.append("file", fs.createReadStream(file.path));
>  form.append('site', site);
    form.append('environment', environment);

>    var mothod = 'PUT'
>    var url = "http://localhost:8000/" + method;
>    xhr.open(method, url);
>    xhr.send(form);
>  }

Error
TypeError: First argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:457:11)
    at exports.XMLHttpRequest.send (/Users/Desktop/proyect/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:467:17)

**Comment by farzonl** [comment]
seems like you need to JSON stringify your form if you want this to work.
