### ISSUE TITLE
Usage with TypeScript and Webpack. Can't resolve 'child_process' error

### ISSUE THREAD

**Issue by vyushin** [driverdan/node-XMLHttpRequest#165]
Hi! Can I use XMLHttpRequest with TypeScript?

I tried this code in `index.ts` file

```typescript
import {XMLHttpRequest} from 'xmlhttprequest';
const request = new XMLHttpRequest();
```

Got error:

![image](https://user-images.githubusercontent.com/8006957/37876252-665e6a78-3052-11e8-93dc-56472289b9fc.png)

**Comment by yankouskia** [comment]
@vyushin if you use webpack, just add 
```js
node: {
  child_process: 'empty',
},
```
to your configuration

**Comment by vyushin** [comment]
@yankouskia, you're right, I used webpack. 
The question does not contain a detailed description.

I am built node.js app written on TS.

**Comment by vyushin** [comment]
@yankouskia, thanks for answer. 
I removed this package from my project. But I remember your solution. :)
